const moviesContent = ['Popular', 'Top Rated', 'Upcoming', 'Now Playing'];

const tvContent = ['Popular', 'Top Rated', 'On TV', 'Airing Today'];

const peopleContent = ['Popular People'];

const visibleContent = [
  'Contribution Bible',
  'Apps',
  'Discussions',
  'Leaderboard',
  'contribute',
  'API',
  'Support',
  'About',
  'Login',
];

const sortMap = {
  'Popularity descending': 'popularity.desc',
  // eslint-disable-next-line sort-keys
  'Popularity Ascending': 'popularity.asc',
  'Rating Ascending': 'rating.asc',
  'Rating descending': 'rating.desc',
  'Release Date Ascending': 'primary_release_date.asc',
  'Release Date descending': 'primary_release_date.desc',
  'title A-Z': 'title.asc',
  'title Z-A': 'title.desc',
};

const filtersList = [
  'Everything',
  "Movies I haven't Seen",
  'Movies I have Seen',
];

const availabilitiesList = [
  'Search all availabilities?',
  'Stream',
  'Free',
  'Ads',
  'Rent',
  'Buy',
];

const releaseList = [
  'Search all Releases?',
  'Search all Countries?',
  'Premier',
  'Theatrical (limited)',
  'Theatrical',
  'Digital',
  'Physical',
  'Tv',
];

const basicContent = [
  'About TMDB',
  'Contact Us',
  'Support Forums',
  'API',
  'System Status',
];

const involvedContent = [
  'Contribution Bible',
  'ADd new movie',
  'Add new TV show',
];

const communityContent = [
  'Guidelines',
  'Discussions',
  'Leaderboard',
  'Twitter',
];

const LegalContent = ['Terms OF Use', 'API Terms OF Use', 'Privacy Policy'];

const predictionsList = [
  'Jurassic World Dominion',
  'The Black Phone',
  'Lightyear',
  'Thor: Love and Thunder',
  'Resident Evil',
  'Doctor Strange  in the Multiverse Madness',
  'Stranger Things',
  'The Forgiven : Part 2. The Other One',
  'Virgin River',
];

const genresList = [
  'Action',
  'Adventure',
  'Animation',
  'Comedy',
  'Crime',
  'Documentary',
  'Drama',
  'Family',
  'Fantasy',
  'History',
  'Horror',
  'Music',
  'Mystery',
  'Romance',
  'Science Fiction',
  'TV Movie',
  'Thriller',
  'War',
  'Western',
];
// length 142
const languagesList = [
  'None Selected',
  'Afrikaans',
  'Albanian',
  'Amharic',
  'Arabic',
  'Aragonese',
  'Armenian',
  'Azerbaijani',
  'Basque',
  'Belarusian',
  'Bengali',
  'Bosnian',
  'Breton',
  'Bulgarian',
  'Catalan',
  'Central Kurdish',
  'Chinese',
  'Chinese (Hong Kong)',
  'Chinese (Simplified)',
  'Chinese (Traditional)',
  'Corsican',
  'Croatian',
  'Czech',
  'Danish',
  'Dutch',
  'English',
  'English (Australia)',
  'English (Canada)',
  'English (India)',
  'English (New Zealand)',
  'English (South Africa)',
  'English (United Kingdom)',
  'English (United States)',
  'Esperanto',
  'Estonian',
  'Filipino',
  'Finnish',
  'French',
  'French (Canada)',
  'French (France)',
  'French (Switzerland)',
  'Galician',
  'Georgian',
  'German',
  'German (Austria)',
  'German (Germany)',
  'German (Liechtenstein)',
  'German (Switzerland)',
  'Greek',
  'Guarani',
  'Gujarati',
  'Hausa',
  'Hawaiian',
  'Hebrew',
  'Hindi',
  'Hungarian',
  'Icelandic',
  'Indonesian',
  'Interlingua',
  'Irish',
  'Italian',
  'Italian (Italy)',
  'Italian (Switzerland)',
  'Japanese',
  'Kannada',
  'Kazakh',
  'Khmer',
  'Korean',
  'Kurdish',
  'Kyrgyz',
  'Lao',
  'Latin',
  'Latvian',
  'Lithuanian',
  'Macedonian',
  'Malay',
  'Malayalam',
  'Maltese',
  'Marathi',
  'Mongolian',
  'Nepali',
  'Norwegian',
  'Pashto',
  'Persian',
  'Polish',
  'Portuguese',
  'Portuguese (Brazil)',
  'Portuguese (Portugal)',
  'Punjabi',
  'Quechua',
  'Romanian',
  'Romanian (Moldova)',
  'Romansh',
  'Russian',
  'Scottish Gaelic',
  'Serbian',
  'Sindhi',
  'Sinhala',
  'Slovak',
  'Slovenian',
  'Somali',
  'Southern Sotho',
  'Spanish',
  'Spanish (Argentina)',
  'Spanish (Latin America)',
  'Spanish (Mexico)',
  'Spanish (Spain)',
  'Spanish (United States)',
  'Sundanese',
  'Swahili',
  'Swedish',
  'Tajik',
  'Tamil',
  'Tatar',
  'Telugu',
  'Thai',
  'Tigrinya',
  'Tongan',
  'Turkish',
  'Turkmen',
  'Twi',
  'Ukrainian',
  'Urdu',
  'Uyghur',
  'Uzbek',
  'Vietnamese',
  'Walloon',
  'Welsh',
  'Western Frisian',
  'Xhosa',
  'Yiddish',
  'Yoruba',
  'Zulu',
];

const urls = {
  desktopLogo:
    'https://www.themoviedb.org/assets/2/v4/logos/v2/blue_short-8e7b30f73a4020692ccca9c88bafe5dcb6f8a62a4c6bc55cd9ba82bb2cd95f6c.svg',
  moviesAPI:
    'https://api.themoviedb.org/3/discover/movie/?api_key=1ed03abf259db3275f034b5a5abe9f9e&language=en-US',
  moviesImage: 'https://image.tmdb.org/t/p/w500',
};
export {
  predictionsList,
  basicContent,
  LegalContent,
  communityContent,
  involvedContent,
  moviesContent,
  peopleContent,
  tvContent,
  visibleContent,
  filtersList,
  sortMap,
  releaseList,
  availabilitiesList,
  genresList,
  languagesList,
  urls,
};
